// Code generated by mockery v2.12.2. DO NOT EDIT.

package invoice

import (
	entities "github.com/Capstone-Project-Kelompok-39-alta/Backend-Capstone-Alta-Golang/entities"
	mock "github.com/stretchr/testify/mock"
)

// InvoiceRepository is an autogenerated mock type for the InvoiceRepository type
type InvoiceRepository struct {
	mock.Mock
}

// CreateInvoiceRepository provides a mock function with given fields: invoice
func (_m *InvoiceRepository) CreateInvoiceRepository(invoice entities.Invoice) error {
	ret := _m.Called(invoice)

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.Invoice) error); ok {
		r0 = rf(invoice)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllInvoiceRepository provides a mock function with given fields:
func (_m *InvoiceRepository) GetAllInvoiceRepository() ([]entities.Invoice, error) {
	ret := _m.Called()

	var r0 []entities.Invoice
	if rf, ok := ret.Get(0).(func() []entities.Invoice); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Invoice)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInvoiceUserRepository provides a mock function with given fields: id
func (_m *InvoiceRepository) GetInvoiceUserRepository(id int) (entities.Invoice, error) {
	ret := _m.Called(id)

	var r0 entities.Invoice
	if rf, ok := ret.Get(0).(func(int) entities.Invoice); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.Invoice)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
