// Code generated by mockery v2.12.2. DO NOT EDIT.

package payment_status

import (
	entities "github.com/Capstone-Project-Kelompok-39-alta/Backend-Capstone-Alta-Golang/entities"
	mock "github.com/stretchr/testify/mock"
)

// PaymentStatusService is an autogenerated mock type for the PaymentStatusService type
type PaymentStatusService struct {
	mock.Mock
}

// CreateInvoicePaymentStatusService provides a mock function with given fields: payment
func (_m *PaymentStatusService) CreateInvoicePaymentStatusService(payment entities.InvoicePaymentStatus) error {
	ret := _m.Called(payment)

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.InvoicePaymentStatus) error); ok {
		r0 = rf(payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteInvoicePaymentStatusByIDService provides a mock function with given fields: id
func (_m *PaymentStatusService) DeleteInvoicePaymentStatusByIDService(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllInvoicesPaymentStatusService provides a mock function with given fields:
func (_m *PaymentStatusService) GetAllInvoicesPaymentStatusService() []entities.InvoicePaymentStatus {
	ret := _m.Called()

	var r0 []entities.InvoicePaymentStatus
	if rf, ok := ret.Get(0).(func() []entities.InvoicePaymentStatus); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.InvoicePaymentStatus)
		}
	}

	return r0
}

// GetInvoicePaymentStatusByIDService provides a mock function with given fields: id
func (_m *PaymentStatusService) GetInvoicePaymentStatusByIDService(id int) (entities.InvoicePaymentStatus, error) {
	ret := _m.Called(id)

	var r0 entities.InvoicePaymentStatus
	if rf, ok := ret.Get(0).(func(int) entities.InvoicePaymentStatus); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entities.InvoicePaymentStatus)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateInvoicePaymentStatusByIDService provides a mock function with given fields: id, payment
func (_m *PaymentStatusService) UpdateInvoicePaymentStatusByIDService(id int, payment entities.InvoicePaymentStatus) error {
	ret := _m.Called(id, payment)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, entities.InvoicePaymentStatus) error); ok {
		r0 = rf(id, payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
