// Code generated by mockery v2.12.2. DO NOT EDIT.

package send_customer

import (
	entities "github.com/Capstone-Project-Kelompok-39-alta/Backend-Capstone-Alta-Golang/entities"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// SendCustomerRepository is an autogenerated mock type for the SendCustomerRepository type
type SendCustomerRepository struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: message
func (_m *SendCustomerRepository) SendEmail(message entities.SendCustomer) error {
	ret := _m.Called(message)

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.SendCustomer) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSendCustomerRepository creates a new instance of SendCustomerRepository. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewSendCustomerRepository(t testing.TB) *SendCustomerRepository {
	mock := &SendCustomerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
