// Code generated by mockery v2.12.2. DO NOT EDIT.

package upload_csv

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// UploadCsvService is an autogenerated mock type for the UploadCsvService type
type UploadCsvService struct {
	mock.Mock
}

// UploadCsv provides a mock function with given fields: File_csv
func (_m *UploadCsvService) UploadCsv(File_csv string) {
	_m.Called(File_csv)
}

// NewUploadCsvService creates a new instance of UploadCsvService. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewUploadCsvService(t testing.TB) *UploadCsvService {
	mock := &UploadCsvService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
