// Code generated by mockery v2.12.2. DO NOT EDIT.

package upload_CSV

import (
	mock "github.com/stretchr/testify/mock"
)

// UploadCsvRepository is an autogenerated mock type for the UploadCsvRepository type
type UploadCsvRepository struct {
	mock.Mock
}

// UploadCsv provides a mock function with given fields: File_csv
func (_m *UploadCsvRepository) UploadCsv(File_csv string) {
	_m.Called(File_csv)
}
