name: Pushing To DockerHub Repository and auto Deploy
on:
  pull_request:
    branches:
      - "staging"
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Qemu
        uses: docker/setup-qemu-action@v1
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login To DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sautmanurung234/capstone-project:v1
      - name: ssh aws ec2 and redeploy docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            docker stop capstone-project
            docker container rm capstone-project
            docker images -a -q | xargs docker rmi -f
            cd Backend-Capstone-Alta-Golang
            git pull origin main
            docker-compose down && docker-compose up --build -d